version: "2"

services:
  homepage:
    image: library/nginx:latest
    environment:
      - NGINX_HOST=joonas.tech

    volumes:
      - ./public:/usr/share/nginx/html:ro

    labels:
      - "traefik.backend=static-homepage"
      - "traefik.frontend.rule=Host:joonas.tech"
      - "traefik.docker.network=traefik_default"

    networks:
      - web

networks:
  web:
    external: true
